language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
script:
node_js:
  - '9'
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
